server:
  port: 8081
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://192.168.64.130:3306/guli_pms
    username: root
    data-password: 776528320
  redis:
    host: 192.168.64.130
  cloud:
    nacos:
      config:
        server-addr: 127.0.0.1:8848
mybatis-plus:
  mapper-locations: classpath:mapper/pms/**/*.xml
  global-config:
    db-config:
      id-type: auto
